### ISSUE TITLE
Proposal: Possibility for changing the component name

### ISSUE THREAD

**Issue by akoenig** [reduct/assembler#14]
The `register` method of the new API should provide the possibility for changing component names.

``` js
app.register(MyComponent); // => use `MyComponent` as name

// or

app.register(MyComponent, 'FooComponent'); // => use `FooComponent` as name.
```

**Comment by Inkdpixels** [comment]
:+1: for this

**Comment by grebaldi** [comment]
+1 from my side too, this is absolutely necessary. A few suggestions:

``` js
app.register(MyComponent).as('Some/Thing/Else');
```

This would make the alias implication explicit, thus more readable, or:

``` js
app.register('MyAlias', MyComponent);
```

Since one is used to the key -> value order in reading direction.

Maybe even some explicit namespacing feature makes sense:

``` js
app.namespace('my/awesome/namespace/')
   .register(Foo)
   .register(Bar)
   .register(Peter).as('Erwin');
```

I would further suggest a `registerAll` method, to allow batch registering, which could have a really nice touch considering desctructuring.

Last but not least: I still think, that the component index of assembler needs to be accessible, which could be handled nicely with just having an arbitrary object structure. Now this is hidden from the user behind an API, that I could imagine to be useful in other contexts too. Think of:

``` js
// my_bootstrap.js
AwesomeDependencyInjectionContainer.register(Foo).as('Bar');

// Storch.js
@Inject('storchProperty', 'Bar')
class Storch {
}
```

I'm planning to implement a common `registry` package, that handles these kinds of APIs, so maybe we should coordinate there.

**Comment by akoenig** [comment]
Have to say that I don't like

``` js
app.register('MyAlias', MyComponent);
```

Feels not correct. Reads like: "Register MyAlias". Instead, I really dig:

``` js
app.register(Peter).as('Erwin');
```

but like

``` js
app.register(MyComponent, 'FooComponent')
```

the most. :)

Batch registering could be handled via `register` as well:

``` js
app.register({MyComponent, FooComponent, BarComponent, ZooComponent});
```

Regarding the `componentIndex`: I would love to have a plugin interface which provides access to the actual components and maybe the index. This would be, imho, a clean separation, something like:

``` js
app.use((components, index) => {
    let Foo = index.get('Foo');

    AwesomeDependencyInjectionContainer.register(Foo).as('Bar');
});
```

But I guess that this might be an own proposal :)

**Comment by grebaldi** [comment]
``` js
app.register({MyComponent, FooComponent, BarComponent, ZooComponent});
```

+1, implicit aliasing would then work like:

``` js
app.register({ 'Erwin': Peter, ... });
```

We will need to differentiate between types for the first parameter of `register` though...

---

``` js
app.use((components, index) => {
    let Foo = index.get('Foo');

    AwesomeDependencyInjectionContainer.register(Foo).as('Bar');
});
```

Like that a lot :+1:  Please write a proposal, I have some ideas already :D

But I actually wanted to point out, that there is a certain possibility to have that `register` and `index` pattern at several points throughout the system. And instead of re-creating it for all parts, I'd like to generalize it as far as possible. It might even make sense to share (namespaced?) indices across different parts of the framework. But that's another discussion^^

**Comment by grebaldi** [comment]
Okay, I made up my mind about

``` js
app.register(MyComponent, 'FooComponent')
```

and now I'm also in favor of this solution. The Problem we would face with the chaining solution is, that we couldn't determine the actual register event (abstractly spoken, not in terms of actually firing an event). It would either occur twice or we would have to defer it somehow, until it could safely be considered aliased finally. Both of these are evil.

So sadly, no sugar here :(

**Comment by akoenig** [comment]
Well, the chaining API would be possible as well:

``` js
register (ComponentClass) {
    // Register class in index
    return {
        as(alias) {
             // Rename registration in index
        }
    };
}
```

**Comment by grebaldi** [comment]
yeah, but as stated above, imagine we would like to actually fire an event on registration:

``` js
register (ComponentClass) {
    // Register class in index
    this.emit('registered:' + ComponentClass.name, ComponentClass); // this should never be fired if it's going to be aliased
    return {
        as(alias) {
             // Rename registration in index
             this.emit('registered:' + alias, ComponentClass); // ???
        }
    };
}
```

Even if no event is fired, we would have an intermediate state, in which `ComponentClass.name` would be Schroedingers cat. It could disappear at any given time, whenever `as` is applied.

**Comment by akoenig** [comment]
Yap, understood your point, but thought that "renaming" a component has nothing to do with registering it in the first place and therefore there is no need for emitting an event again.

But as usual, it is the semantics of such a call-chain and the different opinions :)

**Comment by grebaldi** [comment]
I think, renaming is actually not, what we're trying to do here. It's not even aliasing... mhmm... Maybe let's call it addressing to be more clear :) -> correct me, if I'm misunderstanding things here

When I consider the key under which my ComponentClass got registered the address of that ComponentClass, I most certainly want my ComponentClass to accessible with that address at any given point in time. Otherwise there would be side effects when checking for it's existence and stuff... 

But anyway, I'm arguing against my own proposal here :gun: 

I guess it's best to just go for the parameter solution :)
